pythonURL=["https://www.youtube.com/watch?v=4F2m91eKmts"]
commandsForTut=["conda create --name code python=3.6",
                "conda activate code",
                "cd Desktop/CodeDaddies_list",
                "pip install django",
                "django-admin startproject codedaddies_list",
                "cd codedaddies_list",
                "django-admin startapp my_app",
                "cd codedaddies_list;python manage.py runserver",
                "python manage.py makemigrations",
                "python manage.py migrate",
                "python manage.py createsuperuser",
                "pip install bs4",
                "pip install requests",
                "pip freeze(copy to requirements.txt)"]
